version: '3'
services:
  nuxt:
    container_name: nuxt
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/html
    tty: true
