version: "3"

services:
  server:
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
    - ../src:/go/src/github.com/jphacks/F_2205/server/src
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - PORT=${PORT}